"""Built-in ClickHouse schemas for the project-supported Minghu tables."""

from __future__ import annotations


MINGHU_TABLE_COLUMN_TYPES: dict[str, tuple[tuple[str, str], ...]] = {
    "stock_base.daily": (
        ("code", "String"),
        ("date", "Date"),
        ("exg", "UInt8"),
        ("open", "Nullable(Float64)"),
        ("high", "Nullable(Float64)"),
        ("low", "Nullable(Float64)"),
        ("close", "Nullable(Float64)"),
        ("pclose", "Nullable(Float64)"),
        ("change", "Nullable(Float64)"),
        ("pct_chg", "Nullable(Float64)"),
        ("volume", "Nullable(Int64)"),
        ("amount", "Nullable(Float64)"),
        ("hfq", "Nullable(Float64)"),
        ("ztprice", "Nullable(Float64)"),
        ("dtprice", "Nullable(Float64)"),
        ("omax_op", "Nullable(Float64)"),
        ("omin_op", "Nullable(Float64)"),
    ),
    "index_base.daily": (
        ("code", "String"),
        ("date", "Date"),
        ("exg", "UInt8"),
        ("open", "Nullable(Float64)"),
        ("high", "Nullable(Float64)"),
        ("low", "Nullable(Float64)"),
        ("close", "Nullable(Float64)"),
        ("pclose", "Nullable(Float64)"),
        ("volume", "Nullable(Int64)"),
        ("amount", "Nullable(Float64)"),
    ),
    "stock_base.m1": (
        ("code", "String"),
        ("date_time", "DateTime('Asia/Shanghai')"),
        ("exg", "UInt8"),
        ("time_int", "Int32"),
        ("open", "Nullable(Float64)"),
        ("close", "Nullable(Float64)"),
        ("high", "Nullable(Float64)"),
        ("low", "Nullable(Float64)"),
        ("volume", "Nullable(Float64)"),
        ("amount", "Nullable(Float64)"),
        ("date", "Date"),
    ),
    "stock_base.tk": (
        ("code", "String"),
        ("date_time", "DateTime('Asia/Shanghai')"),
        ("time_int", "Int32"),
        ("exg", "UInt8"),
        ("date", "Date"),
        ("pclose", "Nullable(Float64)"),
        ("open", "Nullable(Float64)"),
        ("high", "Nullable(Float64)"),
        ("low", "Nullable(Float64)"),
        ("last", "Nullable(Float64)"),
        ("total_volume", "Nullable(Int64)"),
        ("total_value", "Nullable(Float64)"),
        ("bid1", "Nullable(Float64)"),
        ("bid2", "Nullable(Float64)"),
        ("bid3", "Nullable(Float64)"),
        ("bid4", "Nullable(Float64)"),
        ("bid5", "Nullable(Float64)"),
        ("bid6", "Nullable(Float64)"),
        ("bid7", "Nullable(Float64)"),
        ("bid8", "Nullable(Float64)"),
        ("bid9", "Nullable(Float64)"),
        ("bid10", "Nullable(Float64)"),
        ("bidv1", "Nullable(Int64)"),
        ("bidv2", "Nullable(Int64)"),
        ("bidv3", "Nullable(Int64)"),
        ("bidv4", "Nullable(Int64)"),
        ("bidv5", "Nullable(Int64)"),
        ("bidv6", "Nullable(Int64)"),
        ("bidv7", "Nullable(Int64)"),
        ("bidv8", "Nullable(Int64)"),
        ("bidv9", "Nullable(Int64)"),
        ("bidv10", "Nullable(Int64)"),
        ("ask1", "Nullable(Float64)"),
        ("ask2", "Nullable(Float64)"),
        ("ask3", "Nullable(Float64)"),
        ("ask4", "Nullable(Float64)"),
        ("ask5", "Nullable(Float64)"),
        ("ask6", "Nullable(Float64)"),
        ("ask7", "Nullable(Float64)"),
        ("ask8", "Nullable(Float64)"),
        ("ask9", "Nullable(Float64)"),
        ("ask10", "Nullable(Float64)"),
        ("askv1", "Nullable(Int64)"),
        ("askv2", "Nullable(Int64)"),
        ("askv3", "Nullable(Int64)"),
        ("askv4", "Nullable(Int64)"),
        ("askv5", "Nullable(Int64)"),
        ("askv6", "Nullable(Int64)"),
        ("askv7", "Nullable(Int64)"),
        ("askv8", "Nullable(Int64)"),
        ("askv9", "Nullable(Int64)"),
        ("askv10", "Nullable(Int64)"),
        ("num_trades", "Nullable(Int64)"),
        ("trading_phase_code", "Nullable(String)"),
        ("close", "Nullable(Float64)"),
        ("ztprice", "Nullable(Float64)"),
        ("dtprice", "Nullable(Float64)"),
    ),
    "stock_base.zb": (
        ("code", "String"),
        ("date", "Date"),
        ("date_time", "DateTime64(3, 'Asia/Shanghai')"),
        ("exg", "UInt8"),
        ("time_int", "Int32"),
        ("price", "Nullable(Float64)"),
        ("volume", "Nullable(Int64)"),
        ("side", "FixedString(1)"),
        ("type", "FixedString(1)"),
        ("trade_flag", "FixedString(1)"),
        ("chno", "UInt64"),
        ("bidno", "Nullable(Int64)"),
        ("askno", "Nullable(Int64)"),
        ("ordno", "Nullable(Int64)"),
        ("seqno", "UInt64"),
        ("ctype", "FixedString(1)"),
        ("cbidno", "Nullable(Int64)"),
        ("caskno", "Nullable(Int64)"),
    ),
}
